### ISSUE TITLE
Error fetching GoodWe data: ILLEGAL DATA ADDRESS

### ISSUE THREAD

**Issue by JoTec2002** [marcelblijleven/goodwe#55]
Hello,

I'm running an Goodwe gw15k-et Inverter connected via LAN.
Lan Module Firmware Version: V1.2.1.18
Inverter Firmware reportet in HA:  00300034003000360032002d / 02020-04-S01

I'm reciving an error in HA: Error fetching GoodWe data: ILLEGAL DATA ADDRESS

The Error is not present on every data fetch.

I alredy added
```
 logger:
  default: warning
  logs:
    custom_components.goodwe: debug
    goodwe: debug
```

but this didn't seem to get me more debug information.
